<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>geek</artifactId>
        <groupId>com.geekxd</groupId>
        <version>3.9.1-G</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>geek-module-flowable</artifactId>

    <description>
        form表单
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.geekxd</groupId>
            <artifactId>geek-system</artifactId>
        </dependency>

        <dependency>
            <groupId>com.geekxd</groupId>
            <artifactId>geek-module-form</artifactId>
            <version>${geek.version}</version>
        </dependency>

        <!-- Flowable启动引擎 -->
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-spring-boot-starter</artifactId>
            <version>7.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.flowable</groupId>
                    <artifactId>flowable-spring-security</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.googlecode.aviator</groupId>
            <artifactId>aviator</artifactId>
            <version>5.3.3</version>
        </dependency>

        <dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js</artifactId>
            <version>24.2.1</version>
            <type>pom</type>
        </dependency>
        
        <dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js-scriptengine</artifactId>
            <version>24.2.1</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

</project>