# generator(代码生成器)模块： 基础配置
gen:
  # 作者
  author: qm.wu
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  # gen_path: /Users/msc/workings/workspace/demo/bt10/tao-end/geek-admin/src 
  packageName: com.geek.tao.bt10
  # 自动去除表前缀，默认是false
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

# flowable(工作流)模块： 基础配置
flowable:
  # 开启定时任务JOB
  async-executor-activate: false
  # 在引擎启动时，会自动更新数据库架构
  database-schema-update: true