<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>geek-scene-pay</artifactId>
        <groupId>com.geekxd</groupId>
        <version>3.9.1-G</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>geek-pay-starter</artifactId>

    <description>
        第三方支付模块
    </description>

    <dependencies>
        <!-- 支付基础模块 -->
        <dependency>
            <groupId>com.geekxd</groupId>
            <artifactId>geek-pay-common</artifactId>
        </dependency>

        <!-- 收钱吧支付 -->
        <dependency>
            <groupId>com.geekxd</groupId>
            <artifactId>geek-pay-sqb</artifactId>
        </dependency>

        <!-- 支付宝支付 -->
        <dependency>
            <groupId>com.geekxd</groupId>
            <artifactId>geek-pay-alipay</artifactId>
        </dependency>

        <!-- 微信支付 -->
        <dependency>
            <groupId>com.geekxd</groupId>
            <artifactId>geek-pay-wx</artifactId>
        </dependency>


    </dependencies>

</project>