-- 数据库连接信息（与 docker bt10-db 一致）
driver=org.postgresql.Driver
url=jdbc:postgresql://127.0.0.1:5432/bt10
username=postgres
password=Bt10@1234
-- liquibse系统表 表名称配置
databaseChangeLogTableName=databasechangelog
databaseChangeLogLockTableName=databasechangeloglock
-- 输出文件路径配置
outputChangeLogFile=geek-admin/src/main/resources/db/changelog/changelog-output-0.0.1.xml
-- liuquibase xml文件路径指定
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
